#!/bin/bash
# 100-intel
# Author: Onifade Moses
# Program: WinMingle Community C Training
# Description: Generates Intel syntax assembly of the C file

gcc -S -masm=intel "$CFILE" -o "${CFILE%.c}.s"

